//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamInformation()
        {
            this.PlayerInformations = new HashSet<PlayerInformation>();
            this.Iteminformations = new HashSet<Iteminformation>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string City { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string CreatYear { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerInformation> PlayerInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iteminformation> Iteminformations { get; set; }
    }
}
